package com.kkvat.automation.service;

import com.kkvat.automation.model.EntityManagement;
import com.kkvat.automation.repository.EntityManagementRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Optional;

@Service
public class EntityGeneratorService {

    private final EntityManagementRepository repository;
    private final EntityManagementService emService;

    public EntityGeneratorService(EntityManagementRepository repository, EntityManagementService emService) {
        this.repository = repository;
        this.emService = emService;
    }

    @Transactional
    public String generate(Long id) throws IOException {
        Optional<EntityManagement> opt = repository.findById(id);
        if (opt.isEmpty()) throw new RuntimeException("EntityManagement not found");
        EntityManagement em = opt.get();

        // Create a target folder under backend/generated/<table>
        Path projectRoot = Path.of(System.getProperty("user.dir"));
        Path target = projectRoot.resolve("generated").resolve(em.getEntityTableName() == null ? em.getEntityName() : em.getEntityTableName());
        Files.createDirectories(target);

        // 1) Create DDL SQL file
        String ddl = buildDDL(em);
        Path ddlFile = target.resolve("create_" + (em.getEntityTableName() != null ? em.getEntityTableName() : em.getEntityName()) + ".sql");
        Files.writeString(ddlFile, ddl, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);

        // 2) Create Java Entity skeleton
        String entityJava = buildEntityJava(em);
        Path javaDir = projectRoot.resolve("backend").resolve("src").resolve("main").resolve("java").resolve("com").resolve("kkvat").resolve("automation").resolve("generated");
        Files.createDirectories(javaDir);
        Path entityFile = javaDir.resolve(capitalize(em.getEntityName()) + ".java");
        Files.writeString(entityFile, entityJava, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);

        // 3) Create Repository skeleton
        String repoJava = buildRepositoryJava(em);
        Path repoFile = javaDir.resolve(capitalize(em.getEntityName()) + "Repository.java");
        Files.writeString(repoFile, repoJava, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);

        // Update status
        emService.setStatus(id, "GENERATED");

        return "Generated at: " + target.toAbsolutePath().toString();
    }

    private String buildDDL(EntityManagement em) {
        String table = em.getEntityTableName() != null ? em.getEntityTableName() : em.getEntityName();
        if (table == null) table = "generated_table";
        StringBuilder sb = new StringBuilder();
        sb.append("-- DDL generated by EntityGeneratorService\n");
        sb.append("CREATE TABLE IF NOT EXISTS ").append(table).append(" (\n");
        sb.append("  id BIGINT AUTO_INCREMENT PRIMARY KEY,\n");
        sb.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n");
        sb.append("  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n");
        sb.append("  name VARCHAR(255)\n");
        sb.append(") ENGINE=InnoDB;\n");
        return sb.toString();
    }

    private String buildEntityJava(EntityManagement em) {
        String className = capitalize(em.getEntityName() == null ? (em.getEntityTableName() == null ? "Generated" : em.getEntityTableName()) : em.getEntityName());
        String table = em.getEntityTableName() != null ? em.getEntityTableName() : em.getEntityName();
        if (table == null) table = "generated_table";
        return "package com.kkvat.automation.generated;\n\n" +
                "import jakarta.persistence.*;\n" +
                "import lombok.*;\n\n" +
                "@Entity\n@Table(name = \"" + table + "\")\n@Data\n@NoArgsConstructor\n@AllArgsConstructor\npublic class " + className + " {\n\n" +
                "    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n\n    private String name;\n\n}";
    }

    private String buildRepositoryJava(EntityManagement em) {
        String className = capitalize(em.getEntityName() == null ? (em.getEntityTableName() == null ? "Generated" : em.getEntityTableName()) : em.getEntityName());
        return "package com.kkvat.automation.generated;\n\n" +
                "import org.springframework.data.jpa.repository.JpaRepository;\n" +
                "import org.springframework.stereotype.Repository;\n\n" +
                "@Repository\npublic interface " + className + "Repository extends JpaRepository<" + className + ", Long> {}\n";
    }

    private String capitalize(String s) {
        if (s == null || s.isBlank()) return "Generated";
        String cleaned = s.replaceAll("[^A-Za-z0-9]", "_");
        return Character.toUpperCase(cleaned.charAt(0)) + cleaned.substring(1);
    }
}
